#theme: minima

permalink: /:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  - 
    scope:
      path: "assets/img"
    values:
      image: true

exclude:
  - .gitignore
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock

exclude: [vendor]
